### PR TITLE
Enable configuration url

### PR DESCRIPTION
**Pull request by fthiery**
Second try for reverted https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/pull/499, please do not merge until https://github.com/home-assistant/core/pull/96107 is shipped

### CODE REVIEW

**Comment by Koenkk** [comment]
Great, this will probably land in the HA 2023.8 release, so let's merge this in September so it will be included in the Z2M October release.

Note when merged: test this on edge addon.

**Comment by fthiery** [comment]
I repushed without one of the `/` chars, or the URL would be 
 `homeassistant:///api/hassio_ingress/1234568`

**Comment by fthiery** [comment]
I managed to test, and this won't work currently (the lovelace UI redirects to the default dashboard instead).

**Comment by fthiery** [comment]
Not stale

**Comment by Koenkk** [comment]
@fthiery ready for merge?

**Comment by fthiery** [comment]
We could merge it right now (HA will not crash anymore), it would display the button, but there are 2 problems with it (both sitting in the UI code):
- the ingress cookie it not automatically set (yet)
- even when it is (e.g. after entering the Z2M frontend once), the UI does not work unless you middle click

I think it would create too much confusion as is, so i'd say we wait until i find the time to figure it out.

**Pull request closed without merging**
