### PR TITLE
Remove Z2M configuration from addon

### PR DESCRIPTION
**Pull request by joshuaspence**
Applies the changes from #270 to `stable`.

#### Checklist
- [x] PR done against `dev` branch
- [x] Updated `zigbee2mqtt/config.json` with new version
- [x] Updated `zigbee2mqtt/CHANGELOG.md` file with new changes
- [ ] Updated `zigbee2mqtt/DOCS.md` with any changes
- [x] Add any new configuration options to `zigbee2mqtt/config.json` and `zigbee2mqtt-edge/config.json`.

### CODE REVIEW

**Comment by joshuaspence** [comment]
@Koenkk I haven't tested this because:

1. It is a bit tricky to test any changes to the Docker image. One suggestion would be to add `dev` in addition to `stable` and `edge`. `dev` would be similar to `edge` but would build the image locally instead of pulling a pre-built container.
2. There's no real changes here. This is basically just syncing `edge` to `stable`.

**Comment by joshuaspence** [comment]
Will check out the build failures a bit later

**Comment by joshuaspence** [comment]
Ah I see. It is assumed that the Z2M version is the same as the addon version.

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
