### PR TITLE
readded scripts folder

### PR DESCRIPTION
**Pull request by bruvv**
Readded script folder which is usefull
And also updated PR template since there is no version information in the dockerfile anymore.

#### Checklist
- [X] PR done against `dev` branch
- [ ] Updated `common/Dockerfile` with new version < this doesn't exists anymore
- [X] Updated `zigbee2mqtt/CHANGELOG.md` file with new changes
- [X] Updated `zigbee2mqtt/DOCS.md` with any changes
- [X] Add any new configuration options to `zigbee2mqtt/config.json` and `zigbee2mqtt-edge/config.json`.

### CODE REVIEW

**Comment by bruvv** [comment]
Any update on this @Koenkk ?

**Comment by Koenkk** [comment]
could you remove the changelog changes and version bump from this mr? then i will include it on the next release on 1 december

**Comment by bruvv** [comment]
Is this what you want @Koenkk :) ?

**Comment by Koenkk** [comment]
yes, thanks!

**Pull request merged**
