### PR TITLE
Remove Z2M configuration from addon

### LINKED ISSUE #41: [Enhancement] Allow editing settings using built-in Zigbee2mqtt web interface
Zigbee2mqtt now has a pretty nice build in web interface. It's also possible to edit most configuration settings using the web interface. These config changes are overwritten by a restart of the add on. This makes the settings part of the interface unusable. All configuration needs to be done in the add on configuration. This is a pity, because the settings in the web interface are actually more comprehensive then what's being passed trough by the add on. (last_seen for example, is missing)

Perhaps it's worth considering to rely on zigbee2mqtt's native web interface for configuration from now on. That way you don't have to keep track of configuration options of zigbee2mqtt in the add on.

Alternatively, you could perhaps make this in itself an option?

### LINKED ISSUE #77: Significant issues/glitches when editing configuration.yaml or restoring backup
I’m having significant trouble with the zigbee2mqtt addon within Home Assistant generally and specifically with attempts to edit the config file or restore a backup.

Every time I use the Home Assistant UI to edit the config file, when I click in the text area, it seems to paste in/duplicate some of the existing config entries and add whitespace at the top or else content disappears and reappears:

Video clip here: https://i.imgur.com/hVQ44oO.mp4

Likely related, restarting Home Assistant completely or even just the addon itself somehow overwrites configuration.yaml and replaces it with what looks like the default config. I've got backups of the /config/zigbee2mqtt folder so I tried deleting the entire folder from Home Assistant and copying back over the known-good backup using samba. I also looked in /share (where I previously stored the configs - could changing this path be the culprit?) to delete anything there. I get the same behaviour even when the addon generates a new zigbee2mqtt folder. The reading/writing of the config file seems completely broken on my system(s) at least. I use Chrome, so also tried Firefox with same issues.

Editing the config file directly also (using Samba to access the file) doesn’t seem to have any effect on the config file loaded in the Home Assistant UI. In fact when I edit configuration.yaml using the Vscode editor plugin for Home Assistant and then restart the zigbee2mqtt addon, the config file seems to also get replaced with default values.

I’ve checked and other addons allow config file editing from the Home Assistant UI in the normal way just fine. I’ve tried completely removing (uninstalling addon and config folders) and re-adding the zigbee2mqtt addon but it still has the same issue of ignoring changes and reloading default config - stored who knows where? I've also restored a backup from a recent Home Assistant snapshot using the HA Snapshot functionality, have the same issue and unfortunately I’ve lost all my devices in zigbee2mqtt.

I've even spun up a VM with a fresh/clean Home Assistant installation and installed _only_ zigbee2mqtt addon with no other config/amendments and it has the same behaviour in the editor window for configuration.yaml

I'm really at a loss now what to do and genuinely think there's a bug either with the addon or with Home Assistant.

In the meantime, what are recommendations for completely purging any old config files used by the addon and then setting it all back up as it was before (I have a backup of the zigbee2mqtt folder). Having said that, I did get the editor glitches and configuration.yaml being overwritten and ignored even with a fresh HA installation.

I'm at a loss here and would appreciate any ideas/help.

**Zigbee2mqtt
Current version: 1.18.1-1**

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
{
  "external_converters": [],
  "devices": [
    "devices.yaml"
  ],
  "groups": [
    "groups.yaml"
  ],
  "homeassistant": true,
  "permit_join": false,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://core-mosquitto",
    "user": "mqtt",
    "password": "*****"
  },
  "serial": {
    "port": "/dev/ttyUSB0"
  },
  "advanced": {
    "ikea_ota_use_test_url": true,
    "log_level": "info",
    "pan_id": 6759,
    "channel": 11,
    "network_key": [
      1,
      3,
      5,
      7,
      9,
      11,
      13,
      15,
      0,
      2,
      4,
      6,
      8,
      10,
      12,
      13
    ],
    "availability_blocklist": [],
    "availability_passlist": []
  },
  "device_options": {},
  "blocklist": [],
  "passlist": [],
  "queue": {},
  "frontend": {
    "port": 8099
  },
  "experimental": {}
}

```

**Running platform (details from Suypervisor > System)**
```
core-2021.3.4
supervisor-2021.03.6
Home Assistant OS 5.12
```

**Your logs from Home Assistant Supervisor**
```
21-03-31 09:19:47 INFO (MainThread) [supervisor.snapshots] Restoring dc719bf1 folders
21-03-31 09:19:47 INFO (SyncWorker_3) [supervisor.snapshots.snapshot] Restore folder share
21-03-31 09:19:47 INFO (SyncWorker_3) [supervisor.snapshots.snapshot] Restore folder share done
21-03-31 09:19:47 INFO (SyncWorker_2) [supervisor.snapshots.snapshot] Restore folder homeassistant
21-03-31 09:19:50 INFO (SyncWorker_2) [supervisor.snapshots.snapshot] Restore folder homeassistant done
21-03-31 09:19:50 INFO (SyncWorker_0) [supervisor.snapshots.snapshot] Restore folder addons/local
21-03-31 09:19:50 INFO (SyncWorker_0) [supervisor.snapshots.snapshot] Restore folder addons/local done
21-03-31 09:19:50 INFO (MainThread) [supervisor.snapshots] Restoring dc719bf1 Repositories
21-03-31 09:19:51 INFO (MainThread) [supervisor.store] Loading add-ons from store: 72 all - 0 new - 0 remove
21-03-31 09:19:51 INFO (MainThread) [supervisor.snapshots] Restoring dc719bf1 old add-ons
21-03-31 09:19:51 INFO (MainThread) [supervisor.addons.addon] Restore config for addon 7ad98f9c_zigbee2mqtt
21-03-31 09:19:51 INFO (MainThread) [supervisor.addons.addon] Restoring data for addon 7ad98f9c_zigbee2mqtt
21-03-31 09:19:52 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-aarch64 with version 1.18.1-1
21-03-31 09:19:52 INFO (SyncWorker_2) [supervisor.docker.interface] Starting homeassistant
21-03-31 09:19:52 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
21-03-31 09:20:15 INFO (MainThread) [supervisor.snapshots] Found 14 snapshot files
21-03-31 09:20:27 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-03-31 09:20:27 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-03-31 09:20:27 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-03-31 09:20:27 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
21-03-31 09:20:27 INFO (MainThread) [supervisor.snapshots] Partial-Restore dc719bf1 done
21-03-31 09:20:35 INFO (SyncWorker_3) [supervisor.docker.interface] Stopping addon_7ad98f9c_zigbee2mqtt application
21-03-31 09:20:39 INFO (SyncWorker_3) [supervisor.docker.interface] Cleaning addon_7ad98f9c_zigbee2mqtt application
21-03-31 09:22:13 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-aarch64 with version 1.18.1-1
21-03-31 09:23:28 INFO (SyncWorker_6) [supervisor.docker.interface] Stopping addon_7ad98f9c_zigbee2mqtt application
21-03-31 09:23:31 INFO (SyncWorker_6) [supervisor.docker.interface] Cleaning addon_7ad98f9c_zigbee2mqtt application
21-03-31 09:24:47 INFO (SyncWorker_7) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-aarch64 with version 1.18.1-1
21-03-31 09:26:37 INFO (SyncWorker_4) [supervisor.docker.interface] Stopping addon_7ad98f9c_zigbee2mqtt application
21-03-31 09:26:41 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_7ad98f9c_zigbee2mqtt application
21-03-31 09:27:23 INFO (SyncWorker_6) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-aarch64 with version 1.18.1-1
21-03-31 09:27:55 INFO (SyncWorker_5) [supervisor.docker.interface] Stopping addon_7ad98f9c_zigbee2mqtt application
21-03-31 09:27:59 INFO (SyncWorker_5) [supervisor.docker.interface] Cleaning addon_7ad98f9c_zigbee2mqtt application
21-03-31 09:28:07 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-03-31 09:28:07 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode
21-03-31 09:28:07 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-03-31 09:28:40 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-03-31 09:29:46 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-aarch64 with version 1.18.1-1
21-03-31 09:31:06 INFO (SyncWorker_6) [supervisor.docker.interface] Stopping addon_7ad98f9c_zigbee2mqtt application
21-03-31 09:31:07 INFO (SyncWorker_6) [supervisor.docker.interface] Cleaning addon_7ad98f9c_zigbee2mqtt application
21-03-31 09:31:14 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
21-03-31 09:31:17 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-03-31 09:31:17 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode
21-03-31 09:31:17 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-03-31 09:32:41 INFO (SyncWorker_6) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-aarch64 with version 1.18.1-1
21-03-31 09:33:10 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
21-03-31 09:33:16 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-03-31 09:33:16 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode
21-03-31 09:33:16 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-03-31 09:33:41 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
21-03-31 09:33:58 INFO (SyncWorker_0) [supervisor.docker.interface] Stopping addon_7ad98f9c_zigbee2mqtt application
21-03-31 09:33:58 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning addon_7ad98f9c_zigbee2mqtt application
21-03-31 09:33:59 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-aarch64 with version 1.18.1-1
21-03-31 09:35:17 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-03-31 09:35:17 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode
21-03-31 09:35:17 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-03-31 09:37:02 INFO (SyncWorker_3) [supervisor.docker.interface] Stopping addon_7ad98f9c_zigbee2mqtt application
21-03-31 09:37:05 INFO (SyncWorker_3) [supervisor.docker.interface] Cleaning addon_7ad98f9c_zigbee2mqtt application
21-03-31 09:37:06 INFO (SyncWorker_6) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-aarch64 with version 1.18.1-1
21-03-31 09:37:26 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.8:8099 ssl:default [Connect call failed ('172.30.33.8', 8099)]
21-03-31 09:37:29 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.8:8099 ssl:default [Connect call failed ('172.30.33.8', 8099)]
21-03-31 09:37:33 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
21-03-31 09:37:42 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-03-31 09:37:42 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode
21-03-31 09:37:42 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-03-31 09:37:59 INFO (SyncWorker_3) [supervisor.docker.interface] Stopping addon_7ad98f9c_zigbee2mqtt application
21-03-31 09:38:03 INFO (SyncWorker_3) [supervisor.docker.interface] Cleaning addon_7ad98f9c_zigbee2mqtt application
21-03-31 09:38:04 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-aarch64 with version 1.18.1-1
21-03-31 09:38:25 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
21-03-31 09:38:35 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-03-31 09:38:35 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode
21-03-31 09:38:36 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-03-31 09:39:14 INFO (MainThread) [supervisor.snapshots] Found 14 snapshot files
21-03-31 09:39:15 INFO (MainThread) [supervisor.snapshots] Found 14 snapshot files
21-03-31 09:39:18 INFO (SyncWorker_6) [supervisor.docker.interface] Stopping addon_7ad98f9c_zigbee2mqtt application
21-03-31 09:39:22 INFO (SyncWorker_6) [supervisor.docker.interface] Cleaning addon_7ad98f9c_zigbee2mqtt application
21-03-31 09:39:25 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
21-03-31 09:39:30 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-03-31 09:39:31 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode
21-03-31 09:39:31 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-03-31 09:39:48 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-aarch64 with version 1.18.1-1
21-03-31 09:40:19 INFO (SyncWorker_3) [supervisor.docker.interface] Stopping addon_7ad98f9c_zigbee2mqtt application
21-03-31 09:40:20 INFO (SyncWorker_3) [supervisor.docker.interface] Cleaning addon_7ad98f9c_zigbee2mqtt application
21-03-31 09:45:11 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-aarch64 with version 1.18.1-1
21-03-31 09:58:01 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-03-31 09:58:01 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
21-03-31 09:58:01 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
21-03-31 09:58:01 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
21-03-31 09:58:01 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-03-31 09:58:01 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
21-03-31 09:58:01 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
21-03-31 09:58:47 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-03-31 09:59:00 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
```

### LINKED ISSUE #109: configuration.yaml file is in JSON format? Plugin not updating, cannot change configuration
**Description of problem:**

SInce 2018.1.1-1 I am getting strange behaviour:

1. Plugin works, 
2. Plugin stopped updating automatically, nor does detect newer version for manual update.
3. When HA starts it is complaining that :
```
21-05-12 12:28:37 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-12 12:28:37 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-12 12:28:37 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
```

I cannot remove them, once I save they always come back in the configuration.

4. I lookend into configuration.yaml and it is in ... json format. I tried to overwrite it with yaml as taken from configuration file, yet it is always coming back in json format. Why is that?

// Please do a short description of the problem
// Make sure your problem is related to the add-on, not to core Zigbee2mqtt functionality, like problems with specific devices - for such issues use https://github.com/Koenkk/zigbee2mqtt/issues

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
// Example:
// > zigbee2mqtt@1.17.0 start /app
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
// replace this line with your pasted configuration
```

**Running platform (details from Suypervisor > System)**
```
// Example
Core: core-2021.2.2
Supervisor: supervisor-2021.02.6
Operating System: HassOS 5.4
```

**Your logs from Home Assistant Supervisor**
```
// Your logs here
```

### PR DESCRIPTION
**Pull request by joshuaspence**
At the moment the addon configuration is very tightly coupled with Zigbee2MQTT's configuration. It seems that the main reason for this is to be able to inject MQTT credentials into Z2M when using an MQTT server provided by another addon (e.g. Mosquitto). My proposal is that instead of controlling and manipulating `configuration.yaml` to inject these credentials, we instead inject them using environment variables. The only possibly confusing thing here is that MQTT settings in `configuration.yaml` would be silently overridden by the addon. We could fix this by checking for `mqtt.server` in `configuration.yaml` and not injecting `ZIGBEE2MQTT_CONFIG_*` environment variables in this case, or by keeping MQTT related settings in the addon config.

The overall idea here is that essential configuration is passed to Zigbee2MQTT as environment variables and users manage Zigbee2MQTT configuration themselves, either through the UI or by manipulating `configuration.yaml`. This approach was inspired by https://github.com/mKeRix/hassio-repo, which does basically the same thing.

Fixes #41. Fixes #77. Fixes #109.

#### Checklist
- [x] PR done against `dev` branch
- [x] Updated `zigbee2mqtt/config.json` with new version
- [x] Updated `zigbee2mqtt/CHANGELOG.md` file with new changes
- [x] Updated `zigbee2mqtt/DOCS.md` with any changes
- [x] Add any new configuration options to `zigbee2mqtt/config.json` and `zigbee2mqtt-edge/config.json`.

### CODE REVIEW

**Comment by Koenkk** [comment]
I like this, but I'm not able to oversee the consequences of this change.

@ciotlosm could you take a look at this?

**Comment by joshuaspence** [comment]
@ciotlosm Any thoughts on this change?

**Comment by Koenkk** [comment]
@joshuaspence would it be an idea to first do this only for the edge version so that this can be properly tested?

**Comment by joshuaspence** [comment]
Sure, makes sense. I'll update it probably tomorrow.

**Comment by ciotlosm** [comment]
Hey. This looks like a great idea.  There was an issue that was raised some time ago for this but we still had no proper way to do this without doing breaking changes. I am happy to go this route but this requires in depths tests to make sure we have all angles covered. I recommend doing some test scenarios for configuration migration and rollback. 

I am currently away and can't look too much into the code but as @Koenkk mentioned it would be vast to try this in edge 1st

**Comment by Koenkk** [comment]
@joshuaspence ready for merge?

**Comment by joshuaspence** [comment]
I'm just testing the roll forward and rollback process.

**Comment by joshuaspence** [comment]
My testing process was as follows:

1. Deploy the stable version from my fork (https://github.com/joshuaspence/hassio-zigbee2mqtt/commit/614f0e12a4858467802ee1f530b38fb772c34d4c). The stable version is essentially unmodified.
2. Configure Z2M through the addon configuration panel.
3. Start the addon and observe that `/config/zigbee2mqtt/configuration.yaml` is JSON created by the addon.
4. Push changes to my fork to remove the addon config (https://github.com/joshuaspence/hassio-zigbee2mqtt/commit/b91c37e17672639c975a0eedbbf56ca09ec1000d)
5. Redeploy Z2M addon.
6. At this point, the addon configuration remained the same (i.e. containing a whole bunch of keys such as `homeassistant` and `permit_join` that are no longer required). Attempting to modify and save the config does log a bunch of warnings to the supervisor logs (e.g. `Option 'availability' does not exist in the schema for Zigbee2mqtt (e135f77f_zigbee2mqtt)`).
7. Observed that Z2M started fine and `configuration.yaml` was still JSON.

I didn't test going backwards (i.e. if we need to revert it) but I'm pretty confident in knowing wha will happen. If users didn't modify there `configuration.yaml` and didn't get rid of the remove addon config then it will go back to the way it was. If users removed the no-longer-needed addon config then they will need to restore it from a backup or manually from `configuration.yaml`. If users made any changes to `configuration.yaml` then those would obviously be wiped out if we went back to addon based configuration.

Let me know if you want me to do any further testing :)

**Comment by Koenkk** [comment]
@joshuaspence reviewed the code and looks good to me, one questions; how can the serial port and MQTT be configured? Because z2m will fail to start if the serial port or MQTT config is incorrect (and thus you cannot reach the frontend)

**Comment by joshuaspence** [comment]
Ah. In that case the file would need to be modified manually, using whatever method the user usually uses for modify Home Assistant configuration files.

I could add back those two options if you'd prefer. Maybe they can be optional so that they can be defined either in the add-on config or the Z2M config file?

**Comment by joshuaspence** [comment]
Question: why can't those options be set through the UI? There are already options that require Z2M to be restarted, I don't think those are different to MQTT server and serial port.

**Comment by joshuaspence** [comment]
@Koenkk I think Koenkk/zigbee2mqtt#10437 broke setting the frontend port with an environment variable. `ZIGBEE2MQTT_CONFIG_FRONTEND_PORT=8099` doesn't seem to have any effect any more.

**Comment by joshuaspence** [comment]
Ok, I have fixed the issue I mentioned above however `ZIGBEE2MQTT_CONFIG_FRONTEND` takes precedence over `frontend` in the config file so that makes it impossible to set other frontend options. Similarly for `homeassistant`, which means that you effectively can't set `homeassistant.legacy_triggers` or `homeassistant.legacy_entity_attributes`.

**Comment by Koenkk** [comment]
> Question: why can't those options be set through the UI? There are already options that require Z2M to be restarted, I don't think those are different to MQTT server and serial port.

Because z2m will not start when the serial port or MQTT config is incorrect, thus you cannot access the frontend. So maybe only these 2 options should be in the configurable

**Comment by joshuaspence** [comment]
Yes but I mean the front-end shod be able to start without MQTT or serial connectivity, I'm guessing that Z2M not starting in this situation is explicitly done in Z2M code?

Is it just `mqtt.server` that is needed to start? Or all `mqtt` options? Similarly, what `serial` options are needed?

**Comment by Koenkk** [comment]
> Yes but I mean the front-end shod be able to start without MQTT or serial connectivity, I'm guessing that Z2M not starting in this situation is explicitly done in Z2M code?

Yes, Z2M will not start

For serial: port, adapter, baudrate and rtscts. Note these all have been moved to serial (https://github.com/Koenkk/zigbee2mqtt.io/blob/develop/docs/guide/configuration/adapter-settings.md)
For mqtt: server, ca, key, cert, user, password

**Comment by Koenkk** [comment]
Thanks!

**Comment by joshuaspence** [comment]
Is edge deployed from `dev` or `master`? Unsure if this is going to be available soon or will need to wait until the next release.

**Comment by netweaver1970** [comment]
Question, will this support a cross-system migration from a Z2M install in a normal docker container (managed using portainer) to a Z2M add-on in HAOS? 
If so, will there be a proper write-up which steps to take to make the migration as painless as possible? 
Currently I'm keeping my old own-managed HA box in the air, only for the Z2M docker instance (and ebusd but also there things are slowly moving towards a HA add-on). 
It would be great to migrate it to my new HA box.

Thanks

**Comment by Koenkk** [comment]
@joshuaspence edge is using dev: https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/blob/c7a85bad7815d6d414bc898d0232160f864c2191/pipeline/edge-build-pipeline.yml#L5 (so it should be in there now)

**Comment by joshuaspence** [comment]
Hmm okay. When I install edge I get the full config options, but maybe that is from the last time I used edge

**Comment by joshuaspence** [comment]
@netweaver1970 I'm not quite sure that I understand your question but I believe you should be able to do that migration with or without this change

**Comment by joshuaspence** [comment]
@Koenkk I think that is only the container? The `config.json` seems to be coming from the `master` branch

**Comment by Koenkk** [comment]
@joshuaspence I see, also merged it to master now

**Comment by joshuaspence** [comment]
Thanks, seems to be working now

**Comment by joshuaspence** [comment]
@Koenkk Just wondering... how long did you want to keep this in edge before copying it across to stable?

**Comment by Koenkk** [comment]
Lets give it another release, this was release on 1 Feb, lets release it in the 1 April release. (will set a reminder)

**Comment by Koenkk** [comment]
@joshuaspence would you mind creating a pr for the non-edge version? Then this can be released with the 1 April release.

**Comment by joshuaspence** [comment]
Sure, done in #307.

**Pull request merged**
