### PR TITLE
Base image updates for s6 v3 and pin to 3.14

### LINKED ISSUE #335: Edge version doesn't launch anymore (fatal: can only run as pid 1)
**Description of problem:**
Edge version fails to launch

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
Edge
```

**Running platform (details from Suypervisor > System)**
```
Core: core-2022.2.9
Supervisor: supervisor-2022.05.1
Operating System: Home Assistant OS 7.4
```

**Your logs from Home Assistant Supervisor**
```
s6-overlay-suexec: fatal: can only run as pid 1
```

### PR DESCRIPTION
**Pull request by mdegat01**
The home assistant base image was updated to s6 v3 which included a few breaking changes detailed [here](https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images). This makes those fixes.

In addition latest for the alpine base image became 3.15 as a part of this and this addon does not seem to work on alpine 3.15. Added a `build.yaml` to pin the version to the alpine 3.14 base image and tweaked the pipeline to use it.

Fixes #335 

#### Checklist
- [x] PR done against `dev` branch
- [x] Updated `zigbee2mqtt/config.json` with new version
- [x] Updated `zigbee2mqtt/CHANGELOG.md` file with new changes
- [x] Updated `zigbee2mqtt/DOCS.md` with any changes
- [x] Add any new configuration options to `zigbee2mqtt/config.json` and `zigbee2mqtt-edge/config.json`.

### CODE REVIEW

**Comment by mdegat01** [comment]
Fwiw I needed to update stable but this doesn't need to be an immediate update to stable. Is there a way to do like a delayed update to stable? Like I just want to make sure that the addon's image builds when Koenkk pushes out an update to Z2M on June 1st. Stable doesn't need to be updated until then.

**Comment by geoffreylagaisse** [comment]
@Koenkk Can you take a look at this please? The edge version doesn't work right now.

**Comment by qp68** [comment]
I tried to reinstall the add-on after reloading/updating the add-ons repositories in HA. I still have the issue and the changelog seems not to have been updated according to the one on Github, is the new build already available ?

Capture d’écran 2022-05-26 à 11 07 49

**Comment by mdegat01** [comment]
@Koenkk yea ok I think I misunderstood the directions. I targetted the dev branch because technically this PR had a fix for stable in it. Not one which required a new version of stable immediately since the existing image works fine. But no new working images for stable could be built without this fix so I thought I should follow those directions.

It looks like doing it that way means this didn't fix edge though. When I pull the `dev` branch locally i can build and run the edge or stable version just fine but installing it from the repo doesn't. Can the commit be cherry picked back to master? Or would you prefer I just make a new PR with the same changes there? I'm on discord btw if you want to just DM me to get this resolved rather then chatting on this closed PR, `CentralCommand#0913`.

**Pull request merged**
