### PR TITLE
Add homeassistant_legacy_entity_attributes option

### PR DESCRIPTION
**Pull request by vturekhanov**
#### Checklist
- [x] PR done against `dev` branch
- [ ] Updated `common/Dockerfile` with new version
- [x] Updated `zigbee2mqtt/CHANGELOG.md` file with new changes
- [ ] Updated `zigbee2mqtt/DOCS.md` with any changes
- [X] Add any new configuration options to `zigbee2mqtt/config.json` and `zigbee2mqtt-edge/config.json`.

### CODE REVIEW

**Comment by darootler** [comment]
Any updates?

Regards
Richard

**Review by darootler — APPROVED** [review]

**Review by ciotlosm — APPROVED** [review]

**Comment by ciotlosm** [comment]
PR must be done against dev branch not master. You must also include in your PR the changelog and version update. Once that is done I will merge this.

**Comment by vturekhanov** [comment]
> PR must be done against dev branch not master. You must also include in your PR the changelog and version update. Once that is done I will merge this.

Done.

**Review by ciotlosm — APPROVED** [review]

**Comment by ciotlosm** [comment]
Can you please open a new PR with "homeassistant_legacy_entity_attributes" also for edge config? I missed the fact that it was not added.

**Pull request merged**
