### PR TITLE
feat: implement proxy addon

### PR DESCRIPTION
**Pull request by SamMousa**
Implements #305 

- Don't use S6overlay since we gain nothing by it when running a single process.
- Single file nginx configuration template for simplicity, most configuration is not needed for a pure proxy.
- Removed `X-Ingress-Path` which I don't think is needed.
- Heavily inspired by @blakeblackshear's frigate proxy; with some minor improvements / simplifications.

I have tested the build locally, but have no easy way to test this in home assistant...

### CODE REVIEW

**Comment by SamMousa** [comment]
I've figured how to run stuff on my local HA instance. This addon now works properly, you can test a dev version by adding my repository. The master branch contains a version that will build on your local HA.

**Comment by SamMousa** [comment]
I have this running locally and it works properly; only thing I haven't figured out is how to use this when running z2m behind a reverse proxy.

Ie my z2m is available on `https://zigbee2mqtt.publicdomain.nl` (which resolves to a local ip 192.168.x.x). But using that in the nginx config leads to some weird path rewriting.

Since this is quite a complex route for the request it'll require some more research, it's not relevant for this PR though.
The path for a request is roughly this:
1. nabucasa reverse proxy
2.  HA ingress reverse proxy
3. nginx addon (this PR)
4. traefik (running ssl termination on my home server)
5. z2m in docker

**Comment by Koenkk** [comment]
In order for this addon to be build; https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/blob/master/.github/workflows/ci.yml has to be updated.

**Comment by SamMousa** [comment]
Yeah ofc, will implement ci after you decide whether you want it.

**Comment by Koenkk** [comment]
Yes I want it 😄

**Comment by SamMousa** [comment]
I've just pushed the commit for CI. Note the new `-n` (no clobber) option for the copy of common files. This allows for files in the addon directories to take priority over common files.

**Comment by Koenkk** [comment]
Thanks!

**Comment by Koenkk** [comment]
@SamMousa I'm trying the addon but I cannot get it working. When opening the proxy it shows the home assistant loading page. I'm 100% sure the server url is correct:

Screenshot 2022-10-22 at 15 24 40


Screenshot 2022-10-22 at 15 24 55

**Comment by SamMousa** [comment]
> I have this running locally and it works properly; only thing I haven't figured out is how to use this when running z2m behind a reverse proxy.
> 
> Ie my z2m is available on `https://zigbee2mqtt.publicdomain.nl` (which resolves to a local ip 192.168.x.x). But using that in the nginx config leads to some weird path rewriting.
> 
> Since this is quite a complex route for the request it'll require some more research, it's not relevant for this PR though. The path for a request is roughly this:
> 
> 1. nabucasa reverse proxy
> 2. HA ingress reverse proxy
> 3. nginx addon (this PR)
> 4. traefik (running ssl termination on my home server)
> 5. z2m in docker

This. I think it's due to zigbee2mqtt not accepting all paths behind a reverse proxy.. Not 100% sure.

**Comment by Koenkk** [comment]
What do you mean with this and how can it be fixed? Does it work for you?

**Comment by SamMousa** [comment]
It works when using the local IP. This is reasonable since HA will do the SSL termination for you so all is encrypted outside the LAN

**Comment by Koenkk** [comment]
I've tried with the local ip but I'm getting the following error:

Screenshot 2022-10-23 at 09 18 15

Screenshot 2022-10-23 at 09 19 42

**Comment by SamMousa** [comment]
Hmm I'll have to give this a proper look from pc. Could be that the build is not the same from what I have locally. Also to be sure, try it without the trailing slash. Nginx proxy behavior changes based on it.

**Comment by Koenkk** [comment]
Work without the `/`! I will updated the docs, thanks!

**Comment by SamMousa** [comment]
Also using the original domain? Or just with IP?

**Comment by Koenkk** [comment]
With the local IP, however one thing that doesn't work yet is the auth token. No popup appears to enter this. I'm wondering if we could add this to the configuration and directly pass it.

**Comment by SamMousa** [comment]
Are you using http basic auth? We could add that easily, same for auth via a bearer token.

**Comment by Koenkk** [comment]
@SamMousa no it is a popup

@nurikk can we allow passing of the auth token via a query parameter?

**Comment by SamMousa** [comment]
I can check how that works. I run z2m unsecured on lan. Let me get back to you.
If we decide to pass an auth token we can do it via a header.

**Comment by nurikk** [comment]
We’re passing token in url (websoket limitation)

**Comment by Koenkk** [comment]
@nurikk but can it be passed before opening the frontend? or does it always needs to be entered in the popup

**Comment by Koenkk** [comment]
Passing the token is now supported in the latest dev branch (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html). E.g. `http://192.168.2.43:8085?token=my_token_123`.

However this does not seem to work in the proxy addon yet:

Screenshot 2022-11-08 at 21 48 28

@SamMousa could you look into this? Without an auth token the frontend is unsafe.

**Comment by nurikk** [comment]
Btw why addon needs nginx proxy? Z2m has own http server and serves static file by itself

**Comment by nurikk** [comment]
Oh, it’s just a proxy 😇

**Comment by SamMousa** [comment]
> Passing the token is now supported in the latest dev branch (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html). E.g. `http://192.168.2.43:8085?token=my_token_123`.
> 
> However this does not seem to work in the proxy addon yet:
> 
> Screenshot 2022-11-08 at 21 48 28
> 
> @SamMousa could you look into this? Without an auth token the frontend is unsafe.

Can we pass the token via a header? That's more secure. If so I can add that to nginx.

**Pull request merged**
