### PR TITLE
Add `advanced.log_output` option to config

### PR DESCRIPTION
**Pull request by mdegat01**
The [Z2M configuration](https://www.zigbee2mqtt.io/information/configuration.html) includes an option to set where the log is output in `advanced.log_output`. It defaults to `file` and `console` but you can adjust it to specify where logging goes or suppress logging entirely. This makes that option available.

#### Checklist
- [x] PR done against `dev` branch
- [ ] Updated `common/Dockerfile` with new version
- [x] Updated `zigbee2mqtt/CHANGELOG.md` file with new changes
- [ ] Updated `zigbee2mqtt/DOCS.md` with any changes
- [x] Add any new configuration options to `zigbee2mqtt/config.json` and `zigbee2mqtt-edge/config.json`.

### CODE REVIEW

**Comment by mdegat01** [comment]
@Koenkk did this go stale or is it rejected? I was hoping to suppress the log file since everything is also in the system journal, the file is just noise on the disk.

**Comment by Koenkk** [comment]
@CodeFinder2 sorry, seems this was done automatically on the 1.19.1-1 release. @ciotlosm can you review this mr?

**Comment by ciotlosm** [comment]
@mdegat01 Can you please update this for latest version with changelog and version update please? I have been away and missed quite a few updates

**Comment by mdegat01** [comment]
@ciotlosm done. Actually I think I forgot to update the `config.json` file before but that's all set now too. I set it to `1.21.0-2` since it looks like you want the first part of the version to match up with the current version number of Z2M right?

Also looking at the checklist, I don't see a version number in `common/Dockerfile`, what should I update for that one? And I looked at `DOCS.md` but wasn't really sure where to put doc on my new config option. Since its just allowing configuration of an existing Z2M option do I need to update `DOCS.md` or is it enough that Z2M already documents the option?

**Review by ciotlosm — APPROVED** [review]

**Comment by ciotlosm** [comment]
The DOCS.md and Dockerfile are there in case there are modifications that require updates in the files. Yours didn't so it's fine

**Pull request merged**
