### PR TITLE
Add frontend port to config

### LINKED ISSUE #262: Frontend not reachable outside of HassIO container
**Description of problem:**
I can only reach the Z2M frontend from within Home-Assistant, not directly from the hostname/ip (e.g. homeassistant.local:8099). 

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
Zigbee2MQTT version 1.22.1-dev commit: 7625d26
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
frontend:
  port: 8099
  host: 0.0.0.0
```

**Running platform (details from Supervisor > System)**
```
// Example
Core: core-2021.12.7
Supervisor: supervisor-2021.12.2
Operating System: HassOS 5.10.63-v8
```

**Proposed solution**
I've cloned the repo to my own repository and this solution works for me:
Add the frontend port to the config.json
```
"ports": {
    "8485/tcp": 8485,
    "8099/tcp": 8099
  },
  "ports_description": {
    "8485/tcp": "Socat tcp-listen port",
    "8099/tcp": "Frontend tcp-listen port"
  },
```

### PR DESCRIPTION
**Pull request by fsfikke**
resolves #262 
#### Checklist
- [x] PR done against `dev` branch
- [x] Updated `zigbee2mqtt/config.json` with new version
- [x] Updated `zigbee2mqtt/CHANGELOG.md` file with new changes
- [ ] Updated `zigbee2mqtt/DOCS.md` with any changes
- [x] Add any new configuration options to `zigbee2mqtt/config.json` and `zigbee2mqtt-edge/config.json`.

### CODE REVIEW

**Review by MatthewsMike — APPROVED** [review]

**Review by ashantyk — APPROVED** [review]

**Comment by ashantyk** [comment]
any chance this PR can be expedited for merge ? i ran into the same problem and the obvious solution was adding the frontend port to config.json

**Comment by joshuaspence** [comment]
I expect most users won't access the frontend directly so it would be better to set the default mapping to `null`, similar to the ESPHome addon.

esphome

**Comment by ashantyk** [comment]
@joshuaspence from a user experience point of view i don't agree with you since this port seems to be required for Home Assistant ingress (unlike the esphome screenshot says) and it will frustrate users that toggle the "Show in sidebar" switch when they see that the frontend won't work out of the box and they need to google it to find out that they need to do some more configuration.

also it's inconsistent. you have the port for socat filled in, but not for the frontend. i'd rather see this (the frontend port) filled in and an `enabled: false` for the frontend section (just like the socat config) than having these mixed ideologies.

but that's just my 2 cents :D

**Comment by joshuaspence** [comment]
> that the frontend won't work out of the box 

On my install the Z2M frontend is working just fine through Home Assistant ingress (via the sidebar link) without exposing port 8099 directly. Can you share your configuration?

> you have the port for socat filled in

IMO the socat port shouldn't be exposed by default either, especially since the default configuration has socat disabled. That will be a backwards incompatible change though and up to the maintainers.

**Comment by ashantyk** [comment]
@joshuaspence 
my config:
```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
serial:
  port: /dev/ttyUSB0
advanced:
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability: false
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
```

clicking the button in the side menu gives a 502 bad gateway error on url:
`http://homeassistant.local:8123/api/hassio_ingress/1bSwcf3bvBpKKxb965LE4uxYu1hbdEyA59SmkS5F_9o/`

using zigbee2mqtt version 1.24.0-1 on HA 2022.3.5 deployed on a Pi4 & using a sonoff zigbee 3.0 dongle (if it matters)

there are no errors on the zigbee2mqtt service log but there are some on the Supervisor; a couple of:
```22-03-20 23:02:07 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)]```

**Comment by joshuaspence** [comment]
That error (`Cannot connect to host 172.30.33.3:8099`) is coming from the Home Assistant supervisor, which doesn't need the port exposed in the way that this PR exposes it. Is there any errors in the Z2M log file? You mentioned the service log which I assume is the stdout/stderr (addon > logs from within the HA U)?

**Comment by ashantyk** [comment]
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[17:14:59] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[17:15:00] INFO: MQTT available, fetching server detail ...
[17:15:00] INFO: MQTT server settings not configured, trying to auto-discovering ...
[17:15:01] INFO: Configuring 'mqtt://core-mosquitto:1883' mqtt server
[17:15:01] INFO: MQTT credentials not configured, trying to auto-discovering ...
[17:15:01] INFO: Configuring'addons' mqtt user
[17:15:01] INFO: Previous config file found, checking backup
[17:15:01] INFO: Creating backup config in '/share/zigbee2mqtt/.configuration.yaml.bk'
[17:15:02] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[17:15:03] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.24.0 start
> node index.js
```
this is all it prints. but i managed to use it (Z2M) by setting `permit_join:true`, joining my zigbee device and reverting the change.

**Comment by joshuaspence** [comment]
Can you change the log level to `info` and make sure the logs contain a line that looks like this:

```
info  2022-03-02 09:53:01: Started frontend on port 0.0.0.0:8099
```

**Comment by ashantyk** [comment]
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[10:18:56] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[10:18:57] INFO: MQTT available, fetching server detail ...
[10:18:57] INFO: MQTT server settings not configured, trying to auto-discovering ...
[10:18:58] INFO: Configuring 'mqtt://core-mosquitto:1883' mqtt server
[10:18:58] INFO: MQTT credentials not configured, trying to auto-discovering ...
[10:18:58] INFO: Configuring'addons' mqtt user
[10:18:58] INFO: Previous config file found, checking backup
[10:18:58] INFO: Creating backup config in '/share/zigbee2mqtt/.configuration.yaml.bk'
[10:18:58] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[10:18:59] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.24.0 start
> node index.js
Zigbee2MQTT:info  2022-03-21 10:19:05: Logging to console and directory: '/share/zigbee2mqtt/log/2022-03-21.10-19-03' filename: log.txt
Zigbee2MQTT:info  2022-03-21 10:19:05: Starting Zigbee2MQTT version 1.24.0 (commit #unknown)
Zigbee2MQTT:info  2022-03-21 10:19:05: Starting zigbee-herdsman (0.14.20)
Zigbee2MQTT:info  2022-03-21 10:19:06: zigbee-herdsman started (resumed)
Zigbee2MQTT:info  2022-03-21 10:19:06: Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20210708,"transportrev":2},"type":"zStack3x0"}'
Zigbee2MQTT:info  2022-03-21 10:19:06: Currently 2 devices are joined:
Zigbee2MQTT:info  2022-03-21 10:19:06: 0x00158d0003e7c3cc (0x00158d0003e7c3cc): WXKG01LM - Xiaomi MiJia wireless switch (EndDevice)
Zigbee2MQTT:info  2022-03-21 10:19:06: 0x60a423fffe25c58d (0x60a423fffe25c58d): GL-C-007P - Gledopto Zigbee LED Controller RGBW (pro) (Router)
Zigbee2MQTT:info  2022-03-21 10:19:06: Zigbee: disabling joining new devices.
Zigbee2MQTT:info  2022-03-21 10:19:06: Connecting to MQTT server at mqtt://core-mosquitto:1883
Zigbee2MQTT:info  2022-03-21 10:19:06: Connected to MQTT server
Zigbee2MQTT:info  2022-03-21 10:19:06: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
Zigbee2MQTT:info  2022-03-21 10:19:07: Started frontend on port 0.0.0.0:8099
Zigbee2MQTT:info  2022-03-21 10:19:07: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"commit":"unknown","coordinator":{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20210708,"transportrev":2},"type":"zStack3x0"},"log_level":"info","network":{"channel":11,"extendedPanID":"0x00124b001cd501f8","panID":6754},"permit_join":false,"version":"1.24.0"}'
[ .... and it starts printing mq messages ... ]
```

**Comment by ashantyk** [comment]
ok...so.. humm... this is gonna sound stupid, but after i put the log level back to warn the frontend started working. i've done restarts of z2m before and it still didn't fixed the issue. at this point i don't know what changed in order to make it work.

**Comment by Koenkk** [comment]
@fsfikke I think the only thing left for merge here is https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/pull/263#issuecomment-1071804359

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
