### PR TITLE
Allow ezsp adapter type

### PR DESCRIPTION
**Pull request by CODeRUS**
Added forgotten adapter for recent release :)

#### Checklist
- [x] PR done against `dev` branch
- [x] Updated `common/Dockerfile` with new version
- [x] Updated `zigbee2mqtt/CHANGELOG.md` file with new changes
- [x] Updated `zigbee2mqtt/DOCS.md` with any changes
- [x] Add any new configuration options to `zigbee2mqtt/config.json` and `zigbee2mqtt-edge/config.json`.

### CODE REVIEW

**Comment by ciotlosm** [comment]
Please update changelog and version to be able to release this after it gets into dev

**Comment by CODeRUS** [comment]
> 
> 
> Please update changelog and version to be able to release this after it gets into dev

Thanks, btw, should i target dev or master, and should i chamge stuff in zigbee2mqtt-edge, zigbee2mqtt or both?

**Comment by ciotlosm** [comment]
In both and target dev please

**Comment by CODeRUS** [comment]
Updated. Please let me know if everything is in orger now :)

**Comment by CODeRUS** [comment]
@ciotlosm hi! is there any extra steps i should do?

**Comment by ciotlosm** [comment]
Don't think so. I will get to a computer today to review and merge

**Comment by DanielPiccoli** [comment]
so glad to see this EZSP adapter piece being added, can`t wait to test it out - btw,  when is this going to the "master" -edge version ?? HA supervisor does not allow me to install a specific branch under DEV, only the -edge itself.

**Pull request merged**
